RuzgarOto.Web/Components/AboutListViewComponent.cs
using _01.RuzgarOto.Entity;
using _03.RuzgarOto.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace RuzgarOto.Web.Components
{
    public class AboutListViewComponent:ViewComponent
    {
        private readonly IAboutServices aboutServices;

        public AboutListViewComponent(IAboutServices aboutServices)
        {
            this.aboutServices = aboutServices;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var val = this.aboutServices.GetAll(false);
            if (val is null)
            {
                return View(Enumerable.Empty<About>());
            }
            return View(val);
        }
    }
}

RuzgarOto.Web/Components/AboutViewComponent.cs
using _01.RuzgarOto.Entity;
using _03.RuzgarOto.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace RuzgarOto.Web.Components
{
    public class AboutViewComponent:ViewComponent
    {
        private readonly IAboutServices aboutServices;
        private readonly ICommunicationServices communicationServices;

        public AboutViewComponent(IAboutServices aboutServices, ICommunicationServices communicationServices)
        {
            this.aboutServices = aboutServices;
            this.communicationServices = communicationServices;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var allValues = this.aboutServices.GetAll();
            var values = allValues.LastOrDefault();
            
            if (values == null)
            {
                // Default About değerleri
                values = new About
                {
                    Id = 0,
                    BaseTitle = "Hakkımızda",
                    Title = "TİA TOPKAPİ OTOMOTİV",
                    Description = "Profesyonel otomotiv hizmetleri sunan firmamız, kaliteli hizmet anlayışı ile müşteri memnuniyetini ön planda tutmaktadır. Uzman ekibimiz ve modern teknoloji ile araçlarınızın bakım ve onarım işlemlerini en iyi şekilde gerçekleştiriyoruz.",
                    ImageName = "",
                    IsActive = true,
                    CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now
                };
            }
            
            // İletişim bilgilerini ViewBag ile gönder
            var communication = this.communicationServices.GetAll().FirstOrDefault();
            ViewBag.Communication = communication;
            
            return View(values);
        }
    }
}

RuzgarOto.Web/Controllers/AboutController.cs
using _01.RuzgarOto.Entity;
using _03.RuzgarOto.Data.Interfaces;
using _04.RuzgarOto.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RuzgarOto.Web.Controllers
{
    [Authorize]
    public class AboutController : Controller
    {
        private readonly IAboutServices _aboutServices;

        public AboutController(IAboutServices aboutServices)
        {
            _aboutServices = aboutServices;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(About about)
        {
            try
            {
                this._aboutServices.Add(about);
                string imageName = this._aboutServices.ImageUpload(about.Image, FileRoad.About);
                about.ImageName = imageName;
                this._aboutServices.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var val = this._aboutServices.GetById(id);
            if (val is not null)
            {
                this._aboutServices.Delete(val);
                this._aboutServices.ImageDelete(val.ImageName, FileRoad.About);
                this._aboutServices.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var val = this._aboutServices.GetById(id);
            return View(val);
        }
        [HttpPost]
        public IActionResult Update(About about)
        {
            var val = this._aboutServices.GetById(about.Id);
            if(about is { Image : null})
            {
                ImageUpdate();
            }
            else
            {
                this._aboutServices.ImageDelete(val.ImageName, FileRoad.About);
                string image =  this._aboutServices.ImageUpload(about.Image, FileRoad.About);
                val.ImageName = image;
                ImageUpdate();
            }



            void ImageUpdate()
            {
                val.BaseTitle = about.BaseTitle;
                val.Title = about.Title;
                val.Description = about.Description;
                val.IsActive = about.IsActive;
                val.UpdatedDate = DateTime.Now;
                this._aboutServices.Update(val);
                this._aboutServices.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }


        [AllowAnonymous]
        public IActionResult About()
        {
            return View();
        }
    }
}

RuzgarOto.Web/Views/About/About.cshtml
@{
    Layout = "_Layout";
}

@await Component.InvokeAsync("About")

RuzgarOto.Web/Views/About/Index.cshtml
@model About

<form method="post" asp-action="Index" asp-controller="About" enctype="multipart/form-data">
    <label asp-for="Image">Resim</label>
    <input asp-for="Image" class="form-control" />
    <br />
    <label asp-for="BaseTitle">Ana Başlık</label>
    <input asp-for="BaseTitle" class="form-control" />
    <br />
    <label asp-for="Title">Başlık</label>
    <input asp-for="Title" class="form-control" />
    <br />
    <label asp-for="Description">Açıklama</label>
    <textarea asp-for="Description" class="form-control w-100" style="height:200px;"></textarea>
    <br />
    <label asp-for="IsActive">Aktif Olsun mu?</label>
    <input asp-for="IsActive" class="form-check" />
    <br />
    <button class="btn btn-dark">Kaydet</button>
</form>
<br />
<br />
@await Component.InvokeAsync("AboutList")

RuzgarOto.Web/Views/About/Update.cshtml
@model About

<form method="post" asp-action="Update" asp-controller="About" enctype="multipart/form-data">
    <label asp-for="Image">Resim</label>
    <input asp-for="Image" class="form-control" />
    <br />
    <label asp-for="BaseTitle">Ana Başlık</label>
    <input asp-for="BaseTitle" class="form-control" />
    <br />
    <label asp-for="Title">Başlık</label>
    <input asp-for="Title" class="form-control" />
    <br />
    <label asp-for="Description">Açıklama</label>
    <textarea asp-for="Description" class="form-control w-100" style="height:200px;"></textarea>
    <br />
    <label asp-for="IsActive">Aktif Olsun mu?</label>
    <input asp-for="IsActive" class="form-check" />
    <br />
    <button class="btn btn-dark">Güncelle</button>
</form>