RuzgarOto.Web/Controllers/PhotoGaleryController.cs
using _01.RuzgarOto.Entity;
using _03.RuzgarOto.Data.Interfaces;
using _04.RuzgarOto.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RuzgarOto.Web.Controllers
{
    [Authorize]
    public class PhotoGaleryController : Controller
    {
        private readonly IPhotoGaleryServices photoGaleryServices;

        public PhotoGaleryController(IPhotoGaleryServices photoGaleryServices)
        {
            this.photoGaleryServices = photoGaleryServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(PhotoGalery photoGalery)
        {
            string imageName = this.photoGaleryServices.ImageUpload(photoGalery.Image, FileRoad.PhotoGalery);
            photoGalery.ImageName = imageName;
            this.photoGaleryServices.Add(photoGalery);
            this.photoGaleryServices.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var val = this.photoGaleryServices.GetById(id);
            this.photoGaleryServices.ImageDelete(val.ImageName, FileRoad.PhotoGalery);
            this.photoGaleryServices.Delete(val);
            this.photoGaleryServices.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var val = this.photoGaleryServices.GetById(id);
            return View(val);
        }
        [HttpPost]
        public IActionResult Update(PhotoGalery photoGalery)
        {
            try
            {
                var val = this.photoGaleryServices.GetById(photoGalery.Id);
                if (photoGalery is { Image: null })
                {
                    Update();
                }
                else
                {
                   
                    this.photoGaleryServices.ImageDelete(val.ImageName, FileRoad.PhotoGalery);
                    string imageName = this.photoGaleryServices.ImageUpload(photoGalery.Image!, FileRoad.PhotoGalery);
                    val.ImageName = imageName;
                    Update();
                }
                void Update()
                {
                    
                    val.IsActive = photoGalery.IsActive;
                    val.UpdatedDate = DateTime.Now;
                    this.photoGaleryServices.Update(val);
                    this.photoGaleryServices.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return NotFound();
            }
            
        }

        ///////////////////////
        ///
        [AllowAnonymous]
        public IActionResult PhotoGalery()
        {
            var values = this.photoGaleryServices.GetAll();
            return View(values);
        }

    }
}

RuzgarOto.Web/Views/PhotoGalery/Index.cshtml
@model PhotoGalery
<form asp-action="Index" asp-controller="PhotoGalery" enctype="multipart/form-data">
    <label asp-for="Image">Resim</label>
    <input asp-for="Image" class="form-control"/>
    <br />
    <label asp-for="IsActive">Aktif Olsun mu?</label>
    <input asp-for="IsActive" class="check-form" checked/>
    <br />
    <button class="btn btn-dark">Kaydet</button>
</form>
<br />
<br />
@await Component.InvokeAsync("PhotoGalery")

RuzgarOto.Web/Views/PhotoGalery/PhotoGalery.cshtml
@{
    Layout = "_Layout";
}
@model IEnumerable<PhotoGalery>
<br />
<br />
<br />
<br />
<!--portfolio start -->
<section id="portfolio" class="portfolio">
    <div class="portfolio-details">
        <div class="section-heading text-center">
            <h2>Fotoğraf Galerimiz</h2>
        </div>
        <div class="container">
            <div class="portfolio-content">
                <div class="isotope">
                    <div class="row">

                        @foreach (var item in Model)
                        {

                            <div class="col-sm-3">
                                <div class="item" style="box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px;">
                                    <img src="~/PhotoGalery/@item.ImageName" alt="portfolio image" style="object-fit:cover;" />
                                </div><!-- /.item -->
                            </div>

                            <!-- /.col -->
                        }


                    </div><!-- /.row -->
                </div><!--/.isotope-->
            </div><!--/.gallery-content-->
        </div><!--/.container-->
    </div><!--/.portfolio-details-->

</section><!--/.portfolio-->
<!--portfolio end -->

RuzgarOto.Web/Views/PhotoGalery/Update.cshtml
@model PhotoGalery

<form asp-action="Update" asp-controller="PhotoGalery" enctype="multipart/form-data">
    <label asp-for="Image">Resim</label>
    <input asp-for="Image" class="form-control" />
    <br />
    <label asp-for="IsActive">Aktif Olsun mu?</label>
    <input asp-for="IsActive" class="check-form" />
    <br />
    <button class="btn btn-dark">Güncelle</button>
</form>